# DailyHotApi Go 版本配置文件
# 这个文件定义了应用运行时需要的所有参数

# 服务器配置
server:
  port: 6688              # HTTP 服务监听端口
  host: "0.0.0.0"         # 监听地址,0.0.0.0 表示接受所有网络接口的请求
  read_timeout: 10s       # 读取请求超时时间
  write_timeout: 10s      # 写入响应超时时间
  prefork: false          # 多进程模式(生产环境建议开启,可以利用多核 CPU)

# 内存缓存配置 (BigCache)
cache:
  enabled: true                # 是否启用内存缓存
  default_expire: 5m           # 默认缓存过期时间(5 分钟)
  cleanup_interval: 10m        # 清理过期缓存的间隔
  max_entries: 10000           # 最大缓存条目数
  max_entry_size: 500          # 单个条目最大大小(字节)
  hard_max_cache_size: 256     # 缓存总大小上限(MB)

# Redis 配置 (分布式缓存)
redis:
  enabled: false          # 是否启用 Redis,本地开发可以关闭
  host: "localhost"       # Redis 服务器地址
  port: 6379              # Redis 端口
  password: ""            # Redis 密码(如果有)
  db: 0                   # 数据库编号(0-15)
  pool_size: 10           # 连接池大小
  timeout: 5s             # 连接超时时间

# 日志配置
log:
  level: "info"              # 日志级别: debug, info, warn, error
  format: "console"          # 输出格式: json(机器可读) 或 console(人类可读)
  output_path: "logs/app.log" # 日志文件路径
  max_size: 100              # 单个日志文件最大大小(MB)
  max_backups: 5             # 保留的旧日志文件数量
  max_age: 30                # 日志文件保留天数
  compress: true             # 是否压缩旧日志文件
